name: flutter_feathersjs_demo_app
description: flutter_feathersjs_demo_app.
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2

  # Navigation
  auto_route: ^1.0.2  
  
  # Communication  with feathers js server
  flutter_feathersjs: ^2.0.3-dev  

  # Local storage
  shared_preferences: ^2.0.5 

  # Service locator
  get_it: ^6.0.0 

  # Bloc for state management
  flutter_bloc: ^7.0.0 
  
  # Value equality
  equatable: ^2.0.0 

  # Functional programming 
  dartz: ^0.10.0-nullsafety.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner:

  # Autoroute generation
  auto_route_generator:  ^1.0.0  

flutter:

  uses-material-design: true